name: Publish

on:
  push:
    branches:
    - master
    tags-ignore:
    - '**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install PNPM
      run: npm i -g pnpm

    - name: Install dependencies
      run: pnpm i --frozen-lockfile

    - name: Build
      run: pnpm build

    - name: Test
      run: pnpm test

    - name: Configure .npmrc
      run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ~/.npmrc
    - name: Publish
      run: pnpm publish
